### ISSUE TITLE
Transfer to an organization

### ISSUE THREAD

**Issue by aminya** [JuliaIO/EzXML.jl#151]
Thank you for this useful library, EzXML. I have been using this in production and my libraries. However, some bugs are remaining that are affecting the functionality of this library.

https://github.com/bicycle1885/EzXML.jl/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

 Because you have already mentioned that you do not check your GitHub, and you do not have much time to devote to this project, could you transfer this repository to some organization? This will allow the community and other developers to have access to the repository and maintain it.

Let me know if you agree with this. I can find a suitable organization for it and prepare the transferring. JuliaData fits the library, in my opinion.

Ref.: Copied from an email I sent to @bicycle1885.

**Comment by BenjaminGalliot** [comment]
@aminya, do you have any news?

**Comment by aminya** [comment]
No unfortunately. I never got an answer. I have created an issue so we can transfer this repository through disputes procedure of General registery

https://github.com/JuliaRegistries/General/issues/25367

**Comment by DilumAluthge** [comment]
@bicycle1885 Are you willing to transfer this repo to the JuliaIO organization?

**Comment by DilumAluthge** [comment]
@ararslan Can you invite @bicycle1885 to join the JuliaIO organization?

**Comment by ararslan** [comment]
Kenta is already in JuliaIO. I've upgraded his permissions to owner to ensure he has the requisite permission to transfer the repository.

**Comment by bicycle1885** [comment]
Im very sorry for my late response. This is completely due to my laziness.

I'm happy to transfer this repository so that some other people can fix problems when I'm not available. Where would be the best place? JuliaIO? JuliaData? IIRC, I suggested tranfering to JuliaIO several years ago, and since now I'm an owner of JuliaIO, JuliaIO is my first choice.

**Comment by ararslan** [comment]
No worries, thanks for chiming in on this. JuliaIO sounds good to me, as it's where LightXML.jl lives.

**Comment by DilumAluthge** [comment]
JuliaIO seems best.

**Comment by bicycle1885** [comment]
Now this has been moved to JuliaIO :+1:

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/pull/26153

**Comment by ararslan** [comment]
Thanks so much, @bicycle1885!

**Comment by DilumAluthge** [comment]
https://github.com/JuliaRegistries/General/pull/26153

**Comment by aminya** [comment]
Can I get an invitation to this repository?
