### ISSUE TITLE
XPath not working as expected with findall

### ISSUE THREAD

**Issue by anandijain** [JuliaIO/EzXML.jl#155]
I cannot seem to make `findall` work as intended. According to https://www.w3schools.com/xml/xpath_syntax.asp, it seems like the Xpath `//ci` should get `compartment`, `k1`, `S1`, but `findall` returns empty Node. 

```xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <apply>
    <times/>
    <ci> compartment 
    </ci>
    <ci> k1 
    </ci>
    <ci> S1 
    </ci>
  </apply>
</math>
```
```julia
julia> findall("//ci", xml)
EzXML.Node[]
```

**Comment by kescobo** [comment]
Your document has a namespace. [See here](https://juliaio.github.io/EzXML.jl/stable/manual/#XPath-1)

In particular:


> There is a caveat on the combination of XPath and namespaces: if a document contains elements with a default namespace, you need to specify its prefix to the find* function. For example, in the following example, the root element and its descendants have a default namespace "http://www.foobar.org", but it does not have its own prefix. In this case, you need to assign a prefix to the namespance when finding elements in the namespace:
>
>```
> julia> doc = parsexml("""
>        <parent xmlns="http://www.foobar.org">
>            <child/>
>        </parent>
>        """)
> EzXML.Document(EzXML.Node(<DOCUMENT_NODE@0x00007fdc67710030>))
> 
> julia> findall("/parent/child", doc.root)  # nothing will be found
> 0-element Array{EzXML.Node,1}
> 
> julia> namespaces(doc.root)  # the default namespace has an empty prefix
> 1-element Array{Pair{String,String},1}:
>  "" => "http://www.foobar.org"
> 
> julia> ns = namespace(doc.root)  # get the namespace
> "http://www.foobar.org"
> 
> julia> findall("/x:parent/x:child", doc.root, ["x"=>ns])  # specify its prefix as "x"
> 1-element Array{EzXML.Node,1}:
>  EzXML.Node(<ELEMENT_NODE[child]@0x00007fdc6774c990>)
>```

**Comment by anandijain** [comment]
Thanks!

**Comment by anandijain** [comment]
@kescobo I have another case here that I think would be better not lost to Slackhole.

```julia
julia> str = """<cn type="e-notation" cellml:units="molar_per_minute">5   <sep/>-2</cn>"""
"<cn type=\"e-notation\" cellml:units=\"molar_per_minute\">5   <sep/>-2</cn>"

julia> parsexml(str)
EzXML.Document(EzXML.Node(<DOCUMENT_NODE@0x0000000002880610>))

julia> parsexml(str).root
ERROR: AssertionError: isempty(XML_GLOBAL_ERROR_STACK)
```

I'm wondering if I can ignore the undefined namespace, basically remove all `cellml:` attributes from a `Document`, or what the standard workaround here is.

I suppose I could do `findall("//*[@cellml:*]", node)` and then just `delete!` the attributes. 
This is sort of an annoying hack, as other formats might have other namespaces. 

If you have any thoughts, I'd really appreciate it!

**Comment by kescobo** [comment]
Alas, I have no idea. The only reason I knew how to answer the previous question is because I'd run into the same issue before and someone else helped me. I'm no expert! Good luck :-/
